Define New Invalid Correlation ID Behavior
smartdevicelink/protocol_spec pull request #25
Opened 2019-04-03 20:10 UTC by JackLivio

Define a behavior for when a request type message contains a correlation id < 0. In this event, core will respond to the mobile library with INVALID_ID.

2019-04-03 21:07 UTC, jacobkeeler requested changes

2019-04-03 21:07 UTC, jacobkeeler commented on README.md
>      <td>32 bits</td>
maybe change to `32 bits (signed)`?

2019-04-04 15:51 UTC, jacobkeeler approved these changes

2019-04-04 19:37 UTC, joeygrover approved these changes

2019-04-04 19:38 UTC, merged